# Generated by Django 5.1.3 on 2024-12-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='member',
            name='registered_at',
        ),
        migrations.CreateModel(
            name='MembershipTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.membership')),
            ],
        ),
    ]
