# Generated by Django 5.1.3 on 2024-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
